const appActions = {
  SET_ENTITY_DATA: "SET_ENTITY_DATA",
  GET_ENTITY_DATA: "GET_ENTITY_DATA",
  SET_SCRUTINIZER_DATA: "SET_SCRUTINIZER_DATA",
  GET_SCRUTINIZER_DATA: "GET_SCRUTINIZER_DATA",
  SET_MEMBER_DATA: "SET_MEMBER_DATA",
  GET_MEMBER_DATA: "GET_MEMBER_DATA",
};

export { appActions };
